apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: client
    git:
      uri: https://github.com/jwennerberg/AI_in_Finance.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
